spring.application.name=potyourholes

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://botme2121_db_user:iWrq8G2fxhHBSN8J@cluster0.vg86grm.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0

# Server port (optional)
server.port=8080

# Logging (optional but helpful)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
