spring.application.name=potyourholes

# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://botme2121_db_user:iWrq8G2fxhHBSN8J@cluster0.vg86grm.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0

# Server port (optional)
server.port=8080

# Logging (optional but helpful)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# =========================
# Google OAuth2 Configuration
# =========================
spring.security.oauth2.client.registration.google.client-id=916738011601-bh0duk6r9i0fedsbdgs98ro0dkgeo3ps.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google


spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


